/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class heightnew_t implements lcm.lcm.LCMEncodable
{
    public float map[][];
 
    public heightnew_t()
    {
        map = new float[101][101];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x30fdefd0a0459084L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.heightnew_t.class))
            return 0L;
 
        classes.add(lcmtypes.heightnew_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        for (int a = 0; a < 101; a++) {
            for (int b = 0; b < 101; b++) {
                outs.writeFloat(this.map[a][b]); 
            }
        }
 
    }
 
    public heightnew_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public heightnew_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.heightnew_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.heightnew_t o = new lcmtypes.heightnew_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.map = new float[(int) 101][(int) 101];
        for (int a = 0; a < 101; a++) {
            for (int b = 0; b < 101; b++) {
                this.map[a][b] = ins.readFloat();
            }
        }
 
    }
 
    public lcmtypes.heightnew_t copy()
    {
        lcmtypes.heightnew_t outobj = new lcmtypes.heightnew_t();
        outobj.map = new float[(int) 101][(int) 101];
        for (int a = 0; a < 101; a++) {
            System.arraycopy(this.map[a], 0, outobj.map[a], 0, 101);        }
 
        return outobj;
    }
 
}

