"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class heightnew_t(object):
    __slots__ = ["map"]

    __typenames__ = ["float"]

    __dimensions__ = [[101, 101]]

    def __init__(self):
        self.map = [ [ 0.0 for dim1 in range(101) ] for dim0 in range(101) ]

    def encode(self):
        buf = BytesIO()
        buf.write(heightnew_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        for i0 in range(101):
            buf.write(struct.pack('>101f', *self.map[i0][:101]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != heightnew_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return heightnew_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = heightnew_t()
        self.map = []
        for i0 in range(101):
            self.map.append(struct.unpack('>101f', buf.read(404)))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if heightnew_t in parents: return 0
        tmphash = (0x30fdefd0a0459084) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if heightnew_t._packed_fingerprint is None:
            heightnew_t._packed_fingerprint = struct.pack(">Q", heightnew_t._get_hash_recursive([]))
        return heightnew_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

